import{S as u,i as f}from"./assets/vendor-46aac873.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d=new URL("/goit-js-hw-11/assets/arrow-icons-a5dab455.svg#icon-left",self.location).href,m=new URL("/goit-js-hw-11/assets/arrow-icons-a5dab455.svg#icon-right",self.location).href,y=new URL("/goit-js-hw-11/assets/error-icon-40fa32d5.svg",self.location).href,i=document.querySelector(".gallery"),p=document.querySelector(".search-photos"),l=document.querySelector(".loader-wrapper"),w=o=>{f.show({title:"ERROR",backgroundColor:"rgba(239, 64, 64, 1)",theme:"dark",message:o,position:"topRight",timeout:5e3,iconUrl:y})},L=o=>{const n=`https://pixabay.com/api/?${new URLSearchParams({key:"41527103-e0775164a767d3baf6162359a",q:encodeURIComponent(o).replace(/%20/g,"+"),image_type:"photo",orientation:"horizontal",safesearch:!0})}`;fetch(n,{}).then(r=>{if(r.ok)return r.json();throw new Error("Sorry, there are some internal mistakes. Please, try reload the page!")}).then(r=>{const e=r.hits;if(r.total===0)throw new Error("Sorry, there are no images matching your search query. Please, try again!");{const t=e.map(({webformatURL:c,largeImageURL:h,tags:g})=>`
                        <li class="gallery-item">
                            <a class="gallery-link" href="${h}">
                                <img
                                    loading="lazy"
                                    class="gallery-image"
                                    src="${c}"
                                    alt="${g}"
                                />
                            </a>
                        </li>
                        `).join("");i.innerHTML=t,new u(".gallery a",{navText:[`<svg width="24" height="24"><use href="${d}"></svg>`,`<svg width="24" height="24"><use href="${m}"></svg>`],captionsData:"alt",captionDelay:!1}).refresh()}}).catch(r=>{w(r.message)}).finally(()=>{l.classList.add("visually-hidden")})},v=o=>{o.preventDefault(),i.innerHTML="",l.classList.remove("visually-hidden");const s=o.target.elements[0].value.trim().toLowerCase().toString();L(s),o.target.reset()};p.addEventListener("submit",v);
//# sourceMappingURL=commonHelpers.js.map
